### ISSUE TITLE
Error al traducir DND

### ISSUE THREAD

**Issue by jactimel** [ravanno/ravanno-dnd5e-es#2]
![imagen_2024-04-01_180357260](https://github.com/ravanno/ravanno-dnd5e-es/assets/23400511/c520486a-8fd0-49a6-893b-c064b4a6643f)
Me sale este error me lo podrias ayudar?

**Comment by ravanno** [comment]
Hola!
Para poder funcionar correctamente, necesitas también tener instalado Babele en su versión 2.5.2 (que es la última disponible hasta la fecha, que yo sepa).
Prueba y me dices.
Saludos.

**Comment by DarkwolfTora** [comment]
Es la que tengo instalada, pero no me deja ni seleccionar el modulo para la traducción al español

**Comment by ravanno** [comment]
He actualizado la compatibilidad para la última versión de Babele que es la 2.5.3.
Prueba a desinstalar el módulo de traducción, actualizar los módulos y volver a instalar el módulo de traducción.
Ya me dices.
Gracias.

**Comment by jactimel** [comment]
Si ya está resuelta muchas gracias
