### ISSUE TITLE
Problemas con los rasgos

### ISSUE THREAD

**Issue by SixStingray8868** [ravanno/ravanno-dnd5e-es#3]
Acabo de instalar el foundry en su versión de 12.324 y lo que pasa es que la traducción tiene un tipo de incompatibilidad con lo de rasgos, cuando se intenta añadir a un personaje que sepa algun idioma, competencia, tirada de salvacion, etc, no aparece nada y no deja pasar de esa pestaña emergente

<img width="722" alt="Captura de pantalla 2024-05-24 202929" src="https://github.com/ravanno/ravanno-dnd5e-es/assets/170780778/3f3908f2-c3eb-484f-a65e-37486739fc40">

**Comment by ravanno** [comment]
He estado revisando lo que comentas y parece que es problema de las traducciones de los compendios realizadas con Babele.
Los he desactivado temporalmente para revisar los archivos. Si actualizas a la nueva versión 3.2.0.2, el asistente debería funcionar bien.
Muchas gracias.

**Comment by SixStingray8868** [comment]
Muchas gracias, ya me lo permitió, excelente el trabajo que llevan, agradezco mucho su esfuerzo

**Comment by ravanno** [comment]
Parece que el problema venía del módulo de Babele. Con la actualizazción 2.5.5 ya funcionan los asistentes de clases y razas teniendo las traducciones de los compendios activas.
También he hecho una revisión completa de los compendios comparando con la versión 3.2.0 del sistema DND5e y se han corregido y actualizado varias cosas.
¡Muchas gracias por la ayuda!
