### ISSUE TITLE
Error modulo 5e 3.3.1

### ISSUE THREAD

**Issue by cx3carloscc** [ravanno/ravanno-dnd5e-es#4]
Buenas, estoy con la versión de 5e 3.3.1 y cuando activo el modulo dentro de la partida y refresca, el babele y libwrapper se me quedan activados pero el modulo de la traducción se desmarca y no se activa.

He hablado con un dev de foundry y me dice que es porque no está habilitado para la versión 3.3.1. se podría fixear? Gracias.

**Comment by ravanno** [comment]
Buenas, muchas gracias por el aviso, se me había pasado esa actualización.
Ya está todo listo para que lo puedas actualizar.
También he relajado las condiciones para los módulos y sistemas necesarios para que no falle y se pueda instalar el módulo de idiomas aunque sea una versión anterior con la nueva y que convivan bien mientras hago las traducciones o mejoras que se necesiten.
Cualquier cosa, por aquí estamos.

**Comment by cx3carloscc** [comment]
Perfecto, muchas gracias, ya he comprobado que se activa sin problemas
