### ISSUE TITLE
SRD Features no traducidas

### ISSUE THREAD

**Issue by cx3carloscc** [ravanno/ravanno-dnd5e-es#5]
Buenas, es normal que las features del SRD no estén traducidas?

**Comment by ravanno** [comment]
Hola. Lo he estado revisando y de los compendios en sí, están bajo revisión y traducción "Classes & Subclass Features (SRD)" y "Monsters (D&D5e)". El resto de compendios deberían aparecen correctamente traducidos (exceptuando las carpetas, que también las estoy revisando).
En cuanto tenga la revisión lista, los publico.
Muchas gracias.

**Comment by cx3carloscc** [comment]
Ah perfecto, pensaba que quizá era cosa mia, muchas gracias

**Comment by ravanno** [comment]
Buenas, he subido una actualización parcial de contenidos del SRD.
En los próximos días iré aplicando más actualizaciones de contenidos.
Muchas gracias.
